### PR TITLE
feat: update directory structure

### PR DESCRIPTION
**Pull request by taichiH**
I've modified directory structure and remove unnecessary aip configurations to keep simpleness. We are supporting only `aip_xx1` in the tutorial.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
## Before

image

image

## After
image

image

image

**Comment by kenji-miyake** [comment]
@taichiH I think we should keep `aip_x1` and `aip_x2` as well.

**Comment by kenji-miyake** [comment]
Also, if the files under `vehicle/` are all `pacmod`-related stuffs, I feel renaming `vehicle/` to `pacmod/` is better.

**Comment by kenji-miyake** [comment]
I guess these files are also vehicle or pacmod related.
image

**Comment by taichiH** [comment]
@kenji-miyake Thank you for the comment. I'll rename `vehicle` to `pacmod` and apply it to https://github.com/tier4/lexus_description.iv/pull/24/files#r813553426

**Comment by wep21** [comment]
(driver/reader/writer.param.yaml have already been removed in jpntaxi.)

**Comment by taichiH** [comment]
@wep21 Thanks. I'll remove them in this PR.

**Comment by taichiH** [comment]
@0x126 
There are no calibration files in `aip_x2` direcotory. Is it better to copy configurations from https://github.com/tier4/aip_description.iv/tree/main/aip_x2_description/config ?

**Comment by 0x126** [comment]
> There are no calibration files in aip_x2 direcotory. Is it better to copy configurations from https://github.com/tier4/aip_description.iv/tree/main/aip_x2_description/config ?

Sorry, I didn't pay attention to this repository because I thought it should always use the forked version.
The aip_x2_description/config is also not updated.

You should copy from https://github.com/tier4/autoware_individual_params.gsm8/tree/develop/ros2/individual_params/config/default/aip_x2

**Comment by taichiH** [comment]
@0x126 These parameters are privately managed, but is it okay to be public?

**Comment by 0x126** [comment]
@taichiH I checked files. You can copy and make public them in `default`

**Comment by taichiH** [comment]
@kenji-miyake @yukkysaito 
Please approve if you don't have any concerns.

**Comment by kenji-miyake** [comment]
I'm not sure whether we should keep `aip_customized` because I think the structure should be defined in forks.
image

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
